version: '3.3'
services:
  springsqlcrud:
    build:
      context: ./
      dockerfile: Dockerfile
#    networks:
#      - mynetwork
#    depends_on:
#      - db
#    command: ["./wait-for-it.sh", "mysqldb:3307", "java", "-jar", "springsqlcrud.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://0.0.0.0:3308/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


#  db:
#    image: mysql:5.7
#    container_name: mysqldb
#    networks:
#      - mynetwork
#    restart: always
#
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_DATABASE: library
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root


#networks:
#  mynetwork: