version: '3'
services:
  springsqlcrud:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
#    network_mode: host
#    hostname: localhost
    ports:
      - 8081:8081

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
    container_name: mysqldb2
#    network_mode: host
#    hostname: localhost
